<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gkillare-win87" failures="1" tests="24" name="testcases.TC_CAN_RefundOfSale" time="1129.032" errors="0" timestamp="2024-06-19T16:36:32 IST" skipped="0">
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard11" time="37.544"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard09" time="68.474"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard16" time="55.682"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard06" time="35.599"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard08" time="52.771"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard10" time="60.610"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard12" time="36.146"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard14" time="35.392">
    <failure message="We are not getting ResponseText as APPROVAL or VALIDATION [null,,374245XXXXX1006,F,1,,AXC,null,0.00,050-DECLINED,20006,291241712289623481,000000000000000000,000000,374245XXXXX1006,AID Not Receive ,AID Not Receive ] expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: We are not getting ResponseText as APPROVAL or VALIDATION [null,,374245XXXXX1006,F,1,,AXC,null,0.00,050-DECLINED,20006,291241712289623481,000000000000000000,000000,374245XXXXX1006,AID Not Receive ,AID Not Receive ] expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at base.BaseClass.performSaleTransaction(BaseClass.java:216)
at testcases.TC_CAN_RefundOfSale.TestCard14(TC_CAN_RefundOfSale.java:309)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCard14 -->
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard05" time="39.641"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard04" time="51.032"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard15" time="30.106"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard02" time="58.788"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard13" time="60.935"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard07" time="18.876"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard05" time="40.165"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard13" time="48.658"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard01" time="58.778"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard06" time="52.775"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard03" time="43.582"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard12" time="57.001"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard10" time="34.772"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard15" time="58.599"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard01" time="32.306"/>
  <testcase classname="testcases.TC_CAN_RefundOfSale" name="TestCard11" time="60.800"/>
</testsuite> <!-- testcases.TC_CAN_RefundOfSale -->
